<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento enterprise edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxlogin
 * @version    1.1.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if ( Mage::helper('ajaxlogin/adminhtml')->isFacebookConfigured() ): ?>
    <script type="text/javascript">
        var __imageNode = $('<?php echo $this->getNetwork()->getButtonHtmlId() ?>');
        __imageNode.observe(
            'click',
            function(imageNode) {
                return function(event) {
                    FB.getLoginStatus(
                        function(imageNode) {
                            return function(response) {
                                if (response.status === 'connected') {
                                    __facebookDoAuth(response.authResponse.accessToken, imageNode);
                                }
                                else {
                                    FB.login(
                                        function (imageNode) {
                                            return function(response) {
                                                if (response.status === 'connected') {
                                                    __facebookDoAuth(imageNode);
                                                }
                                            };
                                        }
                                        (imageNode),
                                        { scope: 'email' }
                                    );
                                }
                            };
                        }
                        (imageNode)
                    );
                };
            }
            (__imageNode)
        );
    </script>
<?php endif; ?>