<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento enterprise edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxlogin
 * @version    1.1.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="account-login<?php if (!$this->helper('customer')->isRegistrationAllowed()) echo ' login-only' ?>">
    <div class="page-title">
        <h1>
            <?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
                <?php echo $this->__('Login or Create an Account') ?>
            <?php else: ?>
                <?php echo $this->__('Login'); ?>
            <?php endif; ?>
        </h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('customer.form.login.extra')?>
    <div class="fieldset">
        <div class="col2-set">
            <div class="col-1 registered-users">
                <h2 class="legend"><?php echo $this->__('Registered Customers') ?></h2>
                <p><?php echo $this->__('If you have an account with us, log in using your email address.') ?></p>
                <?php echo $this->getChildHtml('authorization') ?>
                <ul class="form-list">
                    <li class="note">
                        <a href="<?php echo $this->getForgotPasswordUrl() ?>" id="forgotpwdbtn"><?php echo $this->__('Forgot Your Password?') ?></a>
                    </li>
                    <li class="buttons-set">
                        <button type="submit" class="button" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                    </li>
                </ul>
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            </div>
            <?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
                <div class="col-2 new-users">
                    <h2 class="legend"><?php echo $this->__('New Customers') ?></h2>
                    <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
                    <div class="buttons-set">
                        <button type="button" class="button" id="createaccountbtn">
                            <span><span><?php echo $this->__('Register') ?></span></span>
                        </button>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    Event.observe(
        window,
        'load',
        function() {
            $$('.account-login #send2')[0].observe(
                'click',
                function(event) {
                    var __authorizationNode = $('<?php echo $this->getChild('authorization')->getHtmlId() ?>');
                    var __authorization = AjaxLogin.Authorization.__getInstanceByChildnode(__authorizationNode);
                    __authorization.getFrame('login').login();
                }
            );
            $$('.account-login #forgotpwdbtn')[0].observe(
                'click',
                function(event) {
                    var __overlapRootNode = $('<?php echo $this->getLayout()->getBlock('authorization_container_overlap')->getHtmlId() ?>');
                    __overlapRootNode.style.display = '';
                    
                    var __overlapAuthorizationNode = $('<?php echo $this->getLayout()->getBlock('authorization_container_overlap')->getChild('authorization')->getHtmlId() ?>');
                    var __overlapAuthorizationInstance = AjaxLogin.Authorization.__getInstanceByChildnode(__overlapAuthorizationNode);
                    __overlapAuthorizationInstance.switchToFrame('recovery');
                    
                    if (window.event) window.event.cancelBubble = true;
                    if (window.event) window.event.returnValue = false;
                    event.preventDefault();
                    event.stopPropagation();
                    return false;
                }
            );
            $$('.account-login #createaccountbtn')[0].observe(
                'click',
                function(event) {
                    var __overlapRootNode = $('<?php echo $this->getLayout()->getBlock('authorization_container_overlap')->getHtmlId() ?>');
                    __overlapRootNode.style.display = '';
                    
                    var __overlapAuthorizationNode = $('<?php echo $this->getLayout()->getBlock('authorization_container_overlap')->getChild('authorization')->getHtmlId() ?>');
                    var __overlapAuthorizationInstance = AjaxLogin.Authorization.__getInstanceByChildnode(__overlapAuthorizationNode);
                    __overlapAuthorizationInstance.switchToFrame('register');
                    
                    if (window.event) window.event.cancelBubble = true;
                    if (window.event) window.event.returnValue = false;
                    event.preventDefault();
                    event.stopPropagation();
                    return false;
                }
            );
        }
    );
</script>