<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento enterprise edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxlogin
 * @version    1.1.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if ( Mage::getStoreConfig('ajaxlogin/login_with_linkedin_account/allowed') ): ?>
    <script type="text/javascript">
        if ( typeof AjaxLogin == 'undefined' ) {
            AjaxLogin = {};
        }
        
        AjaxLogin.OAUTH_ACTION_GETAUTHORIZATIONSTATUS   = '<?php echo Mage::helper('ajaxlogin/data')->getUrlSafeForAjax('ajaxlogin/oauth/getAuthorizationStatus') ?>';
        AjaxLogin.OAUTH_ACTION_CHECKAUTHORIZATIONSTATUS = '<?php echo Mage::helper('ajaxlogin/data')->getUrlSafeForAjax('ajaxlogin/oauth/checkAuthorizationStatus') ?>';
        
        if ( typeof AjaxLogin.LinkedIn == 'undefined' ) {
            AjaxLogin.LinkedIn = {};
        }
        
        AjaxLogin.LinkedIn.auth = function(authorizationInstance) {
            window.__authWindow = open(
                AjaxLogin.OAUTH_ACTION_CHECKAUTHORIZATIONSTATUS + '?network=linkedin',
                'linkedinAuth',
                'width=500,height=420,toolbar=no,scrollbars=yes'
            );
            
            window.__authWindowInterval = setInterval(
                function() {
                    if ( (typeof window.__authWindow != 'undefined') && (window.__authWindow.closed) ) {
                        clearInterval(window.__authWindowInterval);
                        AjaxLogin.LinkedIn.getStatus();
                    }
                },
                50
            );
        };
        
        AjaxLogin.LinkedIn.getStatus = function(noTokenCallback, authorizationInstance) {
            if ( typeof authorizationInstance != 'undefined' ) {
                authorizationInstance.__scheduleProgressBar();
            }
            
            new Ajax.Request(
                AjaxLogin.OAUTH_ACTION_GETAUTHORIZATIONSTATUS,
                {
                    method     : 'get',
                    parameters : { network: 'linkedin' },
                    onSuccess: function(transport) {
                        try { eval('var __response = ' + transport.responseText + ';'); }
                        catch (__E) { __response = {}; }
                        
                        if ( typeof __response.access_token_accepted != 'undefined' ) {
                            if ( typeof __response.account_data != 'undefined' ) {
                                AjaxLogin.LinkedIn.login(__response.account_data);
                            }
                        }
                        else {
                            if ( typeof noTokenCallback == 'function' ) {
                                noTokenCallback(__response);
                            }
                        }
                        
                        if ( typeof authorizationInstance != 'undefined' ) {
                            authorizationInstance.__hideProgressBar();
                        }
                    },
                    onFailure: function() {
                        if ( typeof authorizationInstance != 'undefined' ) {
                            authorizationInstance.__hideProgressBar();
                        }
                    }
                }
            );
        };
        
        AjaxLogin.LinkedIn.login = function(linkedinResponse) {
            var __overlapAuthorizationNode = $('<?php echo $this->getLayout()->getBlock('authorization_container_overlap')->getChild('authorization')->getHtmlId() ?>');
            var __overlapAuthorizationInstance = AjaxLogin.Authorization.__getInstanceByChildnode(__overlapAuthorizationNode);
            
            __overlapAuthorizationInstance.getFrame('extra').login(
                { network: 'linkedin' },
                function(linkedinResponse) {
                    return function(response) {
                        if ( typeof response == 'object' ) {
                            if ( (typeof response.notRegistered != 'undefined') && (response.notRegistered == 1) ) {
                                this.register(
                                    {
                                        network   : 'linkedin',
                                        email     : typeof linkedinResponse.emailAddress != 'undefined' ? linkedinResponse.emailAddress : '',
                                        firstname : typeof linkedinResponse.firstName != 'undefined' ? linkedinResponse.firstName : '',
                                        lastname  : typeof linkedinResponse.lastName != 'undefined' ? linkedinResponse.lastName : ''
                                    }
                                );
                            }
                            if ( (typeof response.errorMessage == 'string') && (response.errorMessage.length) ) {
                                __authorizationInstance = AjaxLogin.Authorization.__getInstanceByChildnode(imageNode);
                                __authorizationInstance.setMessage(response.errorMessage);
                            }
                        }
                    };
                }
                (linkedinResponse)
            );
        };
    </script>
<?php endif; ?>