<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento enterprise edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxlogin
 * @version    1.1.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><script type="text/javascript">
    if ( typeof AjaxLogin == 'undefined' ) {
        AjaxLogin = {};
    }
    
    AjaxLogin.BASE_URL_UNSECURE  = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, false) ?>';
    AjaxLogin.BASE_URL_SECURE    = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true) ?>';
    
    AjaxLogin.BASE_URL           = AjaxLogin.BASE_URL_UNSECURE;
    AjaxLogin.TOPLINKS_SELECTION = '<?php echo Mage::helper('ajaxlogin/data')->getToplinksSelection() ?>';
    
    
    /**
     * 
     */
    AjaxLogin.sameRoutines = function(urlA, urlB) {
        if ( typeof urlA != 'string' ) urlA = urlA.toString();
        if ( typeof urlB != 'string' ) urlB = urlB.toString();
        
        if ( urlA.indexOf(AjaxLogin.BASE_URL_UNSECURE) > -1 ) {
            __routineA_Parts = urlA.split(AjaxLogin.BASE_URL_UNSECURE).join('').split('/').splice(0, 3);
        }
        else if ( urlA.indexOf(AjaxLogin.BASE_URL_SECURE) > -1 ) {
            __routineA_Parts = urlA.split(AjaxLogin.BASE_URL_SECURE).join('').split('/').splice(0, 3);
        }
        else {
            return false;
        }
        
        if ( urlB.indexOf(AjaxLogin.BASE_URL_UNSECURE) > -1 ) {
            __routineB_Parts = urlB.split(AjaxLogin.BASE_URL_UNSECURE).join('').split('/').splice(0, 3);
        }
        else if ( urlB.indexOf(AjaxLogin.BASE_URL_SECURE) > -1 ) {
            __routineB_Parts = urlB.split(AjaxLogin.BASE_URL_SECURE).join('').split('/').splice(0, 3);
        }
        else {
            return false;
        }
        
        for ( var __index = 0; __index < 3; __index++ ) {
            if ( (typeof __routineA_Parts[__index] == 'undefined') || (!__routineA_Parts[__index]) ) {
                __routineA_Parts[__index] = 'index';
            }
            if ( (typeof __routineB_Parts[__index] == 'undefined') || (!__routineB_Parts[__index]) ) {
                __routineB_Parts[__index] = 'index';
            }
        }
        
        __routineA = __routineA_Parts.join('/');
        __routineB = __routineB_Parts.join('/');
        
        return __routineA == __routineB ? true : false;
    };
    
    $$( AjaxLogin.TOPLINKS_SELECTION ).each(
        function(node) {
            if ( AjaxLogin.sameRoutines(node.href, '<?php echo $this->getCustomerAccountLoginURL() ?>') ) {
                Event.observe(
                    node,
                    'click',
                    function(event) {
                        var __overlapRootNode = $$('.al-authorization-container-overlap')[0];
                        __overlapRootNode.style.display = '';
                        var __overlapAuthorizationNode = $$('.al-authorization-container-overlap .al-authorization')[0];
                        var __overlapAuthorizationInstance = AjaxLogin.Authorization.__getInstanceByChildnode(__overlapAuthorizationNode);
                        __overlapAuthorizationInstance.switchToFrame('login');
                        
                        if (window.event) window.event.cancelBubble = true;
                        if (window.event) window.event.returnValue = false;
                        event.preventDefault();
                        event.stopPropagation();
                        
                        return false;
                    }
                );
            }
            if ( AjaxLogin.sameRoutines(node.href, '<?php echo $this->getCustomerAccountLogoutURL() ?>') ) {
                Event.observe(
                    node,
                    'click',
                    function(event) {
                        var __overlapAuthorizationNode = $$('.al-authorization-container-overlap .al-authorization')[0];
                        var __overlapAuthorizationInstance = AjaxLogin.Authorization.__getInstanceByChildnode(__overlapAuthorizationNode);
                        __overlapAuthorizationInstance.getFrame('login').logout();
                        
                        if (window.event) window.event.cancelBubble = true;
                        if (window.event) window.event.returnValue = false;
                        event.preventDefault();
                        event.stopPropagation();
                        return false;
                    }
                );
            }
            if ( AjaxLogin.sameRoutines(node.href, '<?php echo $this->getCustomerAccountRegisterURL() ?>') ) {
                Event.observe(
                    node,
                    'click',
                    function(event) {
                        var __overlapRootNode = $$('.al-authorization-container-overlap')[0];
                        __overlapRootNode.style.display = '';
                        var __overlapAuthorizationNode = $$('.al-authorization-container-overlap .al-authorization')[0];
                        var __overlapAuthorizationInstance = AjaxLogin.Authorization.__getInstanceByChildnode(__overlapAuthorizationNode);
                        __overlapAuthorizationInstance.switchToFrame('register');
                        
                        if (window.event) window.event.cancelBubble = true;
                        if (window.event) window.event.returnValue = false;
                        event.preventDefault();
                        event.stopPropagation();
                        return false;
                    }
                );
            }
        }
    );
    
    
    /**
     * 
     */
    if ( typeof window.mainNav == 'function' ) {
        mainNav("nav", {"show_delay":"100","hide_delay":"100"});
    }
    
    
    /**
     * 
     */
    Event.observe(
        window,
        'load',
        function() {
            if (typeof window.customer_dob != 'undefined') {
                delete window.customer_dob;
                
                var __rootNode = $$('.customer-dob')[0];
                new Varien.DateElement(
                    'container',
                    {
                        month  : Element.select(__rootNode, '.dob-month input')[0],
                        day    : Element.select(__rootNode, '.dob-day input')[0],
                        year   : Element.select(__rootNode, '.dob-year input')[0],
                        full   : Element.select(__rootNode, '.dob-full input')[0],
                        advice : Element.select(__rootNode, '.validation-advice')[0]
                    },
                    true,
                    AjaxLogin.DATE_FORMAT
                );
            }
        }
    );
</script>