<label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
<div class="input-box">
    <input
        type="text"
        name="email"
        value="<?php echo $this->htmlEscape($this->getUsername()) ?>"
        id="<?php if ( $this->getHtmlId() ): ?><?php echo $this->getHtmlId() ?><?php else: ?><?php echo $this->getNameInLayout() ?><?php endif; ?>"
        class="input-text required-entry validate-email"
        title="<?php echo $this->__('Email Address') ?>"
    />
</div>