<div class="al-authorizationform-recovery">
    <form action="<?php echo $this->getRecoveryActionUrl() ?>" method="post" id="password-recovery-form">
        <ul class="form-list">
            <?php foreach ($this->getChildren() as $__childBlock): ?>
                <li>
                    <?php echo $__childBlock->toHtml() ?>
                </li>
                <?php if ( $__childBlock->getNameInLayout() == 'al_auth_rec_title' ): ?>
                    <li>
                        <p class="TextMessage"><?php echo $this->getTextMessage() ?></p>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </form>
</div>