<label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
<div class="input-box">
    <input
        type="password"
        name="confirmation"
        class="input-text required-entry validate-cpassword"
        title="<?php echo $this->__('Confirm Password') ?>"
        id="<?php if ( $this->getHtmlId() ): ?><?php echo $this->getHtmlId() ?><?php else: ?><?php echo $this->getNameInLayout() ?><?php endif; ?>"
    />
</div>