<label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
<div class="input-box">
    <input
        type="password"
        name="password"
        class="input-text required-entry validate-password"
        title="<?php echo $this->__('Password') ?>"
        id="<?php if ( $this->getHtmlId() ): ?><?php echo $this->getHtmlId() ?><?php else: ?><?php echo $this->getNameInLayout() ?><?php endif; ?>"
    />
</div>