<ul class="messages Shaddy" style="display: none;">
    <li class="error-msg">&nbsp;</li>
</ul>
<div class="buttons-set">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <?php if ( $this->shouldDisplayForgotpasswordbutton() ): ?>
        <a href="<?php echo $this->getParentBlock()->getForgotPasswordUrl() ?>" id="<?php echo $this->getForgotpasswordbuttonHtmlId() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a><br />
    <?php endif; ?>
    <?php if ( $this->shouldDisplayCreateaccountbutton() ): ?>
        <a href="<?php echo $this->getParentBlock()->getCreateAccountUrl() ?>" id="<?php echo $this->getCreateaccountbuttonHtmlId() ?>" class="f-left"><?php echo $this->__('Create an Account') ?></a>
    <?php endif; ?>
    <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
</div>

<script type="text/javascript">
    Event.observe(
        window,
        'load',
        function() {
            var __node;
            
            __node = $('<?php echo $this->getForgotpasswordbuttonHtmlId() ?>');
            if ( __node ) __node.observe(
                'click',
                function(event) {
                    AjaxLogin.Authorization.__getInstanceByChildnode(this).switchToFrame('recovery');
                    if (window.event) window.event.cancelBubble = true;
                    if (window.event) window.event.returnValue = false;
                    event.preventDefault();
                    event.stopPropagation();
                    return false;
                }
            );
            
            __node = $('<?php echo $this->getCreateaccountbuttonHtmlId() ?>')
            if ( __node ) __node.observe(
                'click',
                function(event) {
                    AjaxLogin.Authorization.__getInstanceByChildnode(this).switchToFrame('register');
                    if (window.event) window.event.cancelBubble = true;
                    if (window.event) window.event.returnValue = false;
                    event.preventDefault();
                    event.stopPropagation();
                    return false;
                }
            );
        }
    );
</script>