<div class="al-authorizationform-extra">
    <form action="<?php echo $this->getLoginActionUrl() ?>" method="post" id="network-login-form"></form>
    <form action="<?php echo $this->getRegisterActionUrl() ?>" method="post" id="network-register-form">
        <ul class="form-list">
            <?php foreach ($this->getChildren() as $__childBlock): ?>
                <li>
                    <?php echo $__childBlock->toHtml() ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </form>
</div>