<div class="al-authorizationform-register">
    <form action="<?php echo $this->getRegisterActionUrl() ?>" method="post" id="register-form">
        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
        <ul class="form-list">
            <?php foreach ($this->getChildren() as $__childBlock): ?>
                <?php $__html = $__childBlock->toHtml(); ?>
                <?php if ( $__html ): ?>
                    <li>
                        <?php echo $__html ?>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </form>
</div>