<?php if ( Mage::getStoreConfig('ajaxlogin/login_with_twitter_account/allowed') ): ?>
    <script type="text/javascript">
        if ( typeof AjaxLogin == 'undefined' ) {
            AjaxLogin = {};
        }
        
        AjaxLogin.OAUTH_ACTION_GETAUTHORIZATIONSTATUS   = '<?php echo Mage::helper('ajaxlogin/data')->getUrlSafeForAjax('ajaxlogin/oauth/getAuthorizationStatus') ?>';
        AjaxLogin.OAUTH_ACTION_CHECKAUTHORIZATIONSTATUS = '<?php echo Mage::helper('ajaxlogin/data')->getUrlSafeForAjax('ajaxlogin/oauth/checkAuthorizationStatus') ?>';
        
        if ( typeof AjaxLogin.Twitter == 'undefined' ) {
            AjaxLogin.Twitter = {};
        }
        
        AjaxLogin.Twitter.auth = function(authorizationInstance) {
            window.__authWindow = open(
                AjaxLogin.OAUTH_ACTION_CHECKAUTHORIZATIONSTATUS + '?network=twitter',
                'twitterAuth',
                'width=500,height=420,toolbar=no,scrollbars=yes'
            );
            
            window.__authWindowInterval = setInterval(
                function() {
                    if ( (typeof window.__authWindow != 'undefined') && (window.__authWindow.closed) ) {
                        clearInterval(window.__authWindowInterval);
                        AjaxLogin.Twitter.getStatus();
                    }
                },
                50
            );
        };
        
        AjaxLogin.Twitter.getStatus = function(noTokenCallback, authorizationInstance) {
            if ( typeof authorizationInstance != 'undefined' ) {
                authorizationInstance.__scheduleProgressBar();
            }
            
            new Ajax.Request(
                AjaxLogin.OAUTH_ACTION_GETAUTHORIZATIONSTATUS,
                {
                    method     : 'get',
                    parameters : { network: 'twitter' },
                    onSuccess: function(transport) {
                        try { eval('var __response = ' + transport.responseText + ';'); }
                        catch (__E) { __response = {}; }
                        
                        if ( typeof __response.access_token_accepted != 'undefined' ) {
                            if ( typeof __response.account_data != 'undefined' ) {
                                AjaxLogin.Twitter.login(__response.account_data);
                            }
                        }
                        else {
                            if ( typeof noTokenCallback == 'function' ) {
                                noTokenCallback(__response);
                            }
                        }
                        
                        if ( typeof authorizationInstance != 'undefined' ) {
                            authorizationInstance.__hideProgressBar();
                        }
                    },
                    onFailure: function() {
                        if ( typeof authorizationInstance != 'undefined' ) {
                            authorizationInstance.__hideProgressBar();
                        }
                    }
                }
            );
        };
        
        AjaxLogin.Twitter.login = function(twitterResponse) {
            var __overlapAuthorizationNode = $('<?php echo $this->getLayout()->getBlock('authorization_container_overlap')->getChild('authorization')->getHtmlId() ?>');
            var __overlapAuthorizationInstance = AjaxLogin.Authorization.__getInstanceByChildnode(__overlapAuthorizationNode);
            
            __overlapAuthorizationInstance.getFrame('extra').login(
                { network: 'twitter' },
                function(twitterResponse) {
                    return function(response) {
                        if ( typeof response == 'object' ) {
                            if ( (typeof response.notRegistered != 'undefined') && (response.notRegistered == 1) ) {
                                var __prefix    = '';
                                var __firstName = '';
                                var __lastName  = '';
                                
                                var __name = typeof twitterResponse.name != 'undefined' ? twitterResponse.name : null;
                                if ( __name ) {
                                    __name = __name.split(' ');
                                    if ( __name.length == 1 ) {
                                        __firstName = __name[0];
                                    }
                                    if ( __name.length == 2 ) {
                                        __firstName = __name[0];
                                        __lastName  = __name[1];
                                    }
                                    if ( __name.length >= 3 ) {
                                        if ( __name[0].substr(-1) == '.' ) {
                                            __prefix    = __name[0];
                                            __firstName = __name[1];
                                            __lastName  = __name[2];
                                        }
                                        else {
                                            __firstName = __name[0];
                                            __lastName  = __name[1];
                                        }
                                    }
                                }
                                
                                this.register(
                                    {
                                        network   : 'twitter',
                                        firstname : __firstName,
                                        lastname  : __lastName
                                    }
                                );
                            }
                            if ( (typeof response.errorMessage == 'string') && (response.errorMessage.length) ) {
                                __authorizationInstance = AjaxLogin.Authorization.__getInstanceByChildnode(imageNode);
                                __authorizationInstance.setMessage(response.errorMessage);
                            }
                        }
                    };
                }
                (twitterResponse)
            );
        };
    </script>
<?php endif; ?>